submit50:
  files: &submit50_files
    - !exclude "*"
    - !include "*.py"
    - !include "*.csv"
    - !require score.py
    - !require score.csv
  style: false
  
check50:
  files: *submit50_files
